include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - example/build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    # Prefer package imports for library code.
    # avoid_print: false
