name: map_camera_flutter
description: Capture camera images with map and location data.
version: 1.0.0
homepage: https://github.com/galtrhan/map_camera_location_flutter
repository: https://github.com/galtrhan/map_camera_location_flutter

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.12.1
  geolocator: ^14.0.0
  geocoding: ^5.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
